listen:
  host: 0.0.0.0
  port: 3000

postgres:
  host: database
  port: 5432
  username: postgres
  db_name: test
  password: 1234
  ssl_mode: disable

jwt:
  access_secret: accesswarning!07@#&
  access_exp: 18000 #5 hours
