listen:
  host: 0.0.0.0
  port: 3000

postgres:
  # host: database
  host: database
  port: 5432
  username: test
  db_name: test
  password: 1234
  ssl_mode: disable

redis:
  # host: redis
  host: redis
  port: 6390
  password:
  db: 5

jwt:
  access_secret: accesswarning!07@#&
  access_exp: 18000 #5 hours
