listen:
  host: 0.0.0.0
  port: 3000

postgres:
  host: localhost
  port: 5432
  username: test
  db_name: test
  password: 12345
  ssl_mode: disable

jwt:
  access_secret: accesswarning!07@#&
  access_exp: 18000 #5 hours
