version: '3.7'

services:
  backend:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    build: ./
    container_name: test
    ports:
      - '3000:3000'
  db:
    restart: always
    image: postgres:alpine
    container_name: database
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./database/migrations/000001_init_test.up.sql:/docker-entrypoint-initdb.d/000001_init_test.up.sql
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=test
    healthcheck:
      test: ["CMD-SHELL", "psql postgresql://postgres:1234@localhost:5432/test"]
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - "4000:5432"
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6380:6379"  # Map container port 6379 to host port 6380
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  postgres-db:
